version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "triage"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "triage"
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "triage"

  - package-ecosystem: "pip"
    directory: "/services/api"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "triage"

  - package-ecosystem: "pip"
    directory: "/services/worker"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "triage"

  - package-ecosystem: "pip"
    directory: "/services/ai_engine"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "triage"
