blank_issues_enabled: false
contact_links:
  - name: Security Disclosure
    url: https://github.com/tofan79/apps-auto-clipper/security/advisories/new
    about: Please report vulnerabilities privately.
